## 세이브더칠드런  후원실적분석(채널/시간대/광고소재별)

In [2]:
import xlsxwriter
import openpyxl
import pandas as pd
from matplotlib import rc
rc('font', family='Malgun Gothic')

### 채널별, 소재별, 시간대 컬럼으로 세분화작업

In [3]:
df_result = pd.read_excel("./Datas/df_result_fn.xlsx")
df_result.tail()

,Unnamed: 0,Date_x,Daypart_x,Channel_x,Creative_x,Net Price,Audience,SPOT,I/B콜수,정기후원,후원금액
64099,64099,2020-12-13,19시대,연합뉴스,울산 아영이,270270.27027,94084.0,1,2,0,0
64100,64100,2020-12-13,19시대,연합뉴스,울산 아영이,270270.27027,94084.0,1,6,1,20000
64101,64101,2020-12-13,19시대,연합뉴스,울산 아영이,270270.27027,96056.0,1,2,0,0
64102,64102,2020-12-13,19시대,연합뉴스,울산 아영이,270270.27027,96056.0,1,6,1,20000
64103,64103,2020-12-13,21시대,연합뉴스,울산 아영이,0.00000,26031.0,1,2,1,30000

----

## 1. 채널별분석

### -채널별 광고송출량 및 후원실적

In [10]:
by_ch = df_result.groupby("Channel_x").sum().sort_values(by='I/B콜수', ascending=False).reset_index()
by_ch["ROI"] = round(by_ch["후원금액"]*12 / by_ch["Net Price"], 2)
by_ch

,Channel_x,Unnamed: 0,Net Price,Audience,SPOT,I/B콜수,정기후원,후원금액,ROI
0,EBS,113598500,2.534234e+09,6.009883e+08,6352,25164,8164,178721500,0.85
1,MBN Plus,675441866,6.593362e+08,4.917848e+07,14875,15757,4446,90220000,1.64
2,연합뉴스,72307906,1.194508e+09,2.589707e+08,5100,11168,3406,74155000,0.74
3,씨채널,251077687,1.869688e+08,1.863756e+07,8567,8878,2563,52105000,3.34
4,TV CHOSUN2,389546901,6.859663e+08,1.292356e+08,6933,7568,2159,43730000,0.76
5,cineF,96669439,1.672246e+08,5.863708e+06,3772,3988,1151,23415000,1.68
6,CNTV,126189641,2.338394e+08,2.337114e+07,3669,3908,1125,22930000,1.18
7,SPOTV,44917982,7.073654e+07,1.361656e+07,2305,3119,881,19543000,3.32
8,YTN,17227282,4.267871e+08,6.404741e+07,1269,3043,861,19030000,0.54
9,NQQ,124904859,1.581679e+08,1.071009e+07,2294,2418,682,13795000,1.05
10,KBS 스포츠,72937878,3.206667e+08,2.386737e+07,1924,2028,572,11570000,0.43
11,CBS,10805049,1.571576e+08,1.569021e+07,1781,1877,655,14055000,1.07
12,SKY트래블,4968756,2.656248e+07,2.876940e+06,914,1055,289,6140000,2.77
13,CTS,4443058,5.559648e+07,5.559648e+06,653,664,249,5437000,1.17
14,SBS,14441507,1.339836e+08,2.153778e+07,322,562,149,3475000,0.31
15,TV조선,1717190,7.988652e+07,1.326145e+07,274,421,127,2505000,0.38
16,SPOTV+,4208251,9.239931e+06,8.437958e+05,324,368,97,2340000,3.04
17,채널A,2181774,6.953454e+07,1.033787e+07,223,362,121,2560000,0.44
18,평화방송,2480553,1.455895e+07,0.000000e+00,362,352,121,2498332,2.06
19,MBC드라마,500893,3.513622e+07,4.119158e+06,238,343,105,2165000,0.74
20,GTV,671671,7.959182e+06,1.633527e+06,271,332,105,2440000,3.68
21,JTBC4,5411730,1.331374e+07,1.239581e+06,260,312,101,2525000,2.28
22,KBS드라마,1152895,5.767757e+07,4.153435e+06,170,249,92,2055000,0.43
23,Ch.View,737286,1.292137e+07,3.257750e+06,197,237,58,1110000,1.03
24,SPOTV2,6616968,3.902906e+06,1.158104e+06,193,203,70,1620000,4.98
25,DramaH,1260150,5.772525e+06,5.772525e+05,139,144,46,985000,2.05
26,하이라이트,704709,5.440406e+06,5.440406e+05,143,141,53,1120000,2.47
27,KBS2,435397,4.258610e+07,3.195902e+06,58,94,17,410000,0.12
28,MBN,497173,2.164816e+07,3.920448e+06,55,86,25,530000,0.29
29,MBC ON,1957794,4.723724e+06,1.197238e+06,48,69,15,290000,0.74
30,SKY펫파크,252137,2.160699e+06,2.227090e+05,63,60,19,340000,1.89
31,Dramax,400616,5.275081e+06,4.525780e+05,53,59,20,510000,1.16
32,BBS,42190,1.331797e+06,1.331797e+05,53,49,19,385000,3.47
33,더라이프,2233805,6.185567e+05,1.138310e+05,35,42,11,250000,4.85
34,BTN,352041,1.227273e+06,1.227273e+05,29,36,9,160000,1.56
35,채널차이나,36104,9.691431e+05,9.691431e+04,39,34,10,200000,2.48
36,채널J,35284,7.698413e+05,3.327800e+04,24,24,6,120000,1.87
37,EDGETV,3692,2.275641e+06,2.275641e+05,19,20,11,220000,1.16
38,리얼TV,27851,4.593496e+05,1.741000e+04,20,19,3,40000,1.04
39,Olive,395428,1.437126e+06,2.040920e+05,19,18,2,60000,0.50
40,FX,107877,1.269841e+06,3.612600e+04,16,15,4,160000,1.51
41,EBS키즈,148900,1.454034e+05,5.054900e+04,14,15,2,40000,3.30
42,SPOTVG&H,466381,2.813041e+05,3.055300e+04,13,14,6,120000,5.12
43,SKY드라마,3005,9.432624e+05,3.966100e+04,8,10,3,70000,0.89
44,D-ONE,106127,7.017716e+05,8.899000e+04,8,9,3,65000,1.11
45,채널A+,5173,1.896067e+05,2.014800e+04,6,6,5,100000,6.33

### -채널별 상관계수

In [5]:
ch_corr = pd.read_excel("./Datas/coref.xlsx", "Channel")
ch_corr

     Creative  Audience  SPOT
0          전체      0.77  0.41
1         EBS      0.83  0.88
2    MBN Plus      0.80  1.00
3        연합뉴스      0.77  0.80
4  TV Chosun2      0.77  0.80

## 2. 시간대별분석

### -시간별 광고송출량 및 후원실적

In [11]:
by_daypart = df_result.groupby("Daypart_x").sum().sort_values(by='I/B콜수', ascending=False).reset_index()
by_daypart["ROI"] = round(by_daypart["후원금액"]*12 / by_daypart["Net Price"], 2)
by_daypart

,Daypart_x,Unnamed: 0,Net Price,Audience,SPOT,I/B콜수,정기후원,후원금액,ROI
0,19시대,183017115,8.763823e+08,2.109593e+08,6202,13396,3880,83505000,1.14
1,21시대,145118656,1.321604e+09,3.125680e+08,5128,12787,4047,87662500,0.80
2,18시대,180657405,6.067460e+08,9.899360e+07,5824,8506,2612,55270000,1.09
3,20시대,135277950,6.023914e+08,9.631065e+07,4322,8148,2692,56745000,1.13
4,12시대,178291152,6.678446e+08,1.045577e+08,6141,8058,2407,50965000,0.92
5,14시대,170554571,3.992876e+08,6.098655e+07,4940,5905,1661,34472000,1.04
6,13시대,160102709,4.876950e+08,7.609354e+07,4910,5749,1800,37648000,0.93
7,16시대,152317791,3.473685e+08,4.692344e+07,4561,5353,1647,34350000,1.19
8,10시대,194271069,3.881490e+08,3.830045e+07,4901,5350,1542,31915000,0.99
9,11시대,104473688,3.647374e+08,4.846080e+07,3748,4986,1347,28798332,0.95
10,09시대,132039182,3.164980e+08,4.886319e+07,3908,4563,1344,28082000,1.06
11,15시대,141498163,3.201581e+08,4.669147e+07,3967,4563,1372,28555000,1.07
12,17시대,110278686,3.745977e+08,6.094868e+07,3259,4542,1416,29887000,0.96
13,22시대,27332204,2.576044e+08,3.440458e+07,974,1668,611,13235000,0.62
14,08시대,32061406,5.241745e+07,5.067318e+06,895,1120,236,4740000,1.09
15,07시대,5004995,6.910656e+06,2.620652e+05,188,245,22,445000,0.77
16,06시대,817817,7.981906e+06,1.785693e+06,89,127,0,0,0.00
17,23시대,471587,1.065911e+07,1.615331e+06,34,107,2,40000,0.05
18,01시대,268689,1.301503e+06,7.833310e+05,25,43,0,0,0.00
19,02시대,261819,3.329267e+06,5.484810e+05,23,42,0,0,0.00
20,05시대,185730,6.527800e+05,8.869900e+04,26,33,0,0,0.00
21,03시대,163951,1.253601e+06,2.346500e+05,19,25,0,0,0.00
22,04시대,72287,1.938123e+05,1.010000e+03,11,15,0,0,0.00
23,24시대,90734,3.286385e+05,3.286385e+04,9,9,0,0,0.00

### -시간대별 상관계수

In [7]:
dp_corr = pd.read_excel("./Datas/coref.xlsx", "Daypart")
dp_corr

  Daypart  Audience  SPOT
0      전체      0.77  0.41
1    19시대      0.73  0.77
2    20시대      0.83  0.87
3    21시대      0.59  0.87
4    18시대      0.76  0.96
5    12시대      0.66  0.99

## 3. 광고소재별

### -광고소재별 광고송출량 및 후원실적

In [12]:
by_cre = df_result.groupby("Creative_x").sum().sort_values(by='I/B콜수', ascending=False).reset_index()
by_cre["ROI"] = round(by_cre["후원금액"]*12 / by_cre["Net Price"], 2)
by_cre

,Creative_x,Unnamed: 0,Net Price,Audience,SPOT,I/B콜수,정기후원,후원금액,ROI
0,소희편,47177415,1.133046e+09,2.039212e+08,4323,13757,4331,94930000,1.01
1,시설보호지온,67077693,6.586969e+08,1.308862e+08,3124,6241,2035,45358000,0.83
2,싱글대디,17403818,3.879369e+08,8.929679e+07,1737,5689,1284,26922500,0.83
3,JUST신구,47510054,4.302353e+08,1.361988e+08,1969,4245,1604,34420000,0.96
4,심장소리,17763572,4.879383e+08,1.169106e+08,1413,3986,1363,30542000,0.75
5,난방비2,19748357,3.301398e+08,7.085099e+07,1294,3168,899,20085000,0.73
6,카얌베,6545293,2.050048e+08,3.077633e+07,2328,2737,939,20155000,1.18
7,JUST,10582630,1.927534e+08,3.023293e+07,1844,2319,724,15012000,0.93
8,수연이,10098072,2.117051e+08,3.408289e+07,1377,2067,778,16938332,0.96
9,난방비,8212494,1.912086e+08,4.472038e+07,797,2003,528,11527000,0.72
10,울산 아영이,46179320,2.428306e+08,4.922234e+07,735,1495,431,9450000,0.47
11,교육비재윤이,9667737,1.685165e+08,3.179102e+07,518,1426,424,9420000,0.67
12,정읍조손가정,6903590,8.559429e+07,2.518443e+07,393,1032,345,7600000,1.07
13,전주고은이,26352324,7.807252e+07,1.574847e+07,639,969,276,6035000,0.93
14,긴급구호,3937700,7.266365e+07,1.019178e+07,803,847,324,7005000,1.16
15,아동학대,1447496,7.373498e+07,1.187122e+07,487,656,258,5220000,0.85
16,아동학대서연이,4840804,6.527448e+07,1.426752e+07,255,401,149,3540000,0.65
17,싱글대디2,1187620,5.941708e+07,6.635211e+06,174,275,86,1995000,0.40
18,동아프리카,2228332,1.500926e+07,1.535888e+06,224,234,82,1820000,1.46
19,폐렴,2422530,8.486076e+06,7.857280e+05,220,218,52,1035000,1.46
20,존,1309360,6.099394e+06,5.893645e+05,162,158,40,880000,1.73
21,모래벼룩,243700,3.894592e+06,3.557690e+05,95,96,33,720000,2.22
22,브라더스,1294369,7.254309e+06,2.733819e+06,56,83,19,340000,0.56
23,테스티모니얼,1108706,7.410475e+06,7.410475e+05,81,75,28,630000,1.02
24,예맨,865544,6.706419e+06,6.138851e+05,70,74,25,490000,0.88
25,실팔찌,766691,2.727448e+06,6.472520e+05,36,34,4,90000,0.40
26,브랜딩,128281,4.950718e+06,7.381158e+05,23,23,4,75000,0.18
27,진우,8276,1.167315e+05,1.757900e+04,3,4,1,10000,1.03

### -광고소재별 상관계수

In [9]:
cr_corr = pd.read_excel("./Datas/coref.xlsx", "Creative")
cr_corr

  Creative  Audience  SPOT
0       전체      0.77  0.41
1      소희편      0.92  0.91
2   시설보호지원      0.84  0.84
3     싱글대디      0.93  0.85
4   JUST신구      0.78  0.77
5     심장소리      0.92  0.86

### 향후 진행사항 및 개선사항
1. 채널, 시간대, Film별 회귀분석
2. 채널-시간대/Film 별 매칭해보기
3. ROI가 잘 나오는 유사채널 찾기

#### 선생님 코멘트
- 광고의 퀄리티를 반영해봐라 - ex)TVCF 광고평가 같은거?