In [7]:
from IPython.display import Image
import xlsxwriter
import openpyxl
import pandas as pd
from matplotlib import rc
rc('font', family='Malgun Gothic')
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import xlsxwriter
import openpyxl
import pandas as pd
from matplotlib import rc
rc('font', family='Malgun Gothic')
%matplotlib inline
%config InlineBacked.figure_format = {'png', 'retina'}
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from matplotlib import font_manager, rc

font_name = font_manager.FontProperties(fname="c:/Windows/Fonts/malgun.ttf").get_name()
rc('font', family=font_name)

In [8]:
df_result_merged = pd.read_excel("./datas/df_result_merged.xlsx")
df_result_merged = df_result_merged.rename(columns = {"Date_x":"Date", "Daypart_x":"Daypart","Channel_x":"Channel","Creative_x":"Creative"})
df_result_merged.head(4)

,Unnamed: 0,Unnamed: 0.1,Date,Daypart,Channel,Creative,Net Price,Audience,SPOT,I/B콜수,정기후원,후원금액,Category,Material,Asklevel,Model
0,0,0,2018-06-24,08시대,EDGETV,아동학대,128205.128205,12820.512821,1,2,1,20000,국내,아동학대,2만원,실제사례
1,1,4,2018-06-17,08시대,EDGETV,아동학대,128205.128205,12820.512821,1,1,1,20000,국내,아동학대,2만원,실제사례
2,2,12,2018-06-26,09시대,하이라이트,아동학대,41512.915129,4151.291513,1,0,0,0,국내,아동학대,2만원,실제사례
3,3,39,2018-06-16,09시대,하이라이트,아동학대,41512.915129,4151.291513,1,1,0,0,국내,아동학대,2만원,실제사례

In [9]:
by_ch = df_result_merged.groupby("Channel").sum().sort_values(by='후원금액', ascending=False).reset_index()
by_ch["ROI"] = round(by_ch["후원금액"]*12 / by_ch["Net Price"], 2)
by_ch.head(12)

,Channel,Unnamed: 0,Unnamed: 0.1,Net Price,Audience,SPOT,I/B콜수,정기후원,후원금액,ROI
0,EBS,99755574,113598500,2.534234e+09,6.009883e+08,6352,25164,8164,178721500,0.85
1,MBN Plus,692009195,675441866,6.593362e+08,4.917848e+07,14875,15757,4446,90220000,1.64
2,연합뉴스,60683708,72307906,1.194508e+09,2.589707e+08,5100,11168,3406,74155000,0.74
3,씨채널,256996844,251077687,1.869688e+08,1.863756e+07,8567,8878,2563,52105000,3.34
4,TV CHOSUN2,396378044,389546901,6.859663e+08,1.292356e+08,6933,7568,2159,43730000,0.76
5,cineF,100548308,96669439,1.672246e+08,5.863708e+06,3772,3988,1151,23415000,1.68
6,CNTV,129943671,126189641,2.338394e+08,2.337114e+07,3669,3908,1125,22930000,1.18
7,SPOTV,38187304,44917982,7.073654e+07,1.361656e+07,2305,3119,881,19543000,3.32
8,YTN,18302898,17227282,4.267871e+08,6.404741e+07,1269,3043,861,19030000,0.54
9,CBS,10780223,10805049,1.571576e+08,1.569021e+07,1781,1877,655,14055000,1.07
10,NQQ,127616367,124904859,1.581679e+08,1.071009e+07,2294,2418,682,13795000,1.05
11,KBS 스포츠,75212046,72937878,3.206667e+08,2.386737e+07,1924,2028,572,11570000,0.43

In [18]:
arr = []
for j in range(0,46,1) :
    for i in range(10, 24, 1):
        df_result = df_result_merged
        channel = df_result = df_result[df_result['Channel'] == by_ch['Channel'][j]]
        df_result["ROI"]  = round(df_result["후원금액"]*12 / df_result["Net Price"], 2)
        df_result = df_result[df_result['후원금액'] > 0.00]
        df_result = df_result[df_result['Net Price'] > 0.00]
        df_result = df_result[df_result['Daypart'] == f'{i}시대']
        df_result.sort_values(by=['ROI'], axis=0, ascending=False)
        ROI = round(df_result["ROI"].sum() / len(df_result["ROI"]),1)
        arr.append(ROI)
        print(by_ch['Channel'][j],i,"시대  / ", "ROI",ROI)
arr = pd.DataFrame(arr)
arr

EBS 10 시대  /  ROI 0.7
EBS 11 시대  /  ROI 0.9
EBS 12 시대  /  ROI 2.1
EBS 13 시대  /  ROI 1.5
EBS 14 시대  /  ROI 1.2
EBS 15 시대  /  ROI 1.5
EBS 16 시대  /  ROI 1.5
EBS 17 시대  /  ROI 1.5
EBS 18 시대  /  ROI 2.1
EBS 19 시대  /  ROI 1.9
EBS 20 시대  /  ROI 1.7
EBS 21 시대  /  ROI 1.4
EBS 22 시대  /  ROI 1.1
EBS 23 시대  /  ROI 0.5
MBN Plus 10 시대  /  ROI 4.6
MBN Plus 11 시대  /  ROI 4.8
MBN Plus 12 시대  /  ROI 4.7
MBN Plus 13 시대  /  ROI 4.7
MBN Plus 14 시대  /  ROI 4.6
MBN Plus 15 시대  /  ROI 4.7
MBN Plus 16 시대  /  ROI 4.8
MBN Plus 17 시대  /  ROI 4.6
MBN Plus 18 시대  /  ROI 4.8
MBN Plus 19 시대  /  ROI 4.6
MBN Plus 20 시대  /  ROI 4.6
MBN Plus 21 시대  /  ROI 4.8
MBN Plus 22 시대  /  ROI 4.6
MBN Plus 23 시대  /  ROI nan
연합뉴스 10 시대  /  ROI nan
연합뉴스 11 시대  /  ROI 1.5
연합뉴스 12 시대  /  ROI 1.3
연합뉴스 13 시대  /  ROI 1.3
연합뉴스 14 시대  /  ROI 1.3
연합뉴스 15 시대  /  ROI 1.9
연합뉴스 16 시대  /  ROI 1.0
연합뉴스 17 시대  /  ROI 1.8
연합뉴스 18 시대  /  ROI 1.2
연합뉴스 19 시대  /  ROI 1.6
연합뉴스 20 시대  /  ROI 1.6
연합뉴스 21 시대  /  ROI 0.9
연합뉴스 22 시대  /  ROI 1.3
연합뉴스 23 시대  /  ROI nan
씨채널 10 시대  /  ROI 11.6
씨채널 11 시대  /  ROI 11.4
씨채널 12 시대  /  ROI 11.2
씨채널 13 시대  /  ROI 11.5
씨채널 14 시대  /  ROI 11.0
씨채널 15 시대  /  ROI 11.0
씨채널 16 시대  /  ROI 11.6
씨채널 17 시대  /  ROI 11.3
씨채널 18 시대  /  ROI 15.5
씨채널 19 시대  /  ROI 14.2
씨채널 20 시대  /  ROI 11.8
씨채널 21 시대  /  ROI 15.7
씨채널 22 시대  /  ROI nan
씨채널 23 시대  /  ROI nan
TV CHOSUN2 10 시대  /  ROI 2.6
TV CHOSUN2 11 시대  /  ROI 3.9
TV CHOSUN2 12 시대  /  ROI 2.5
TV CHOSUN2 13 시대  /  ROI 2.5
TV CHOSUN2 14 시대  /  ROI 2.6
TV CHOSUN2 15 시대  /  ROI 2.8
TV CHOSUN2 16 시대  /  ROI 3.3
TV CHOSUN2 17 시대  /  ROI 3.0
TV CHOSUN2 18 시대  /  ROI 3.3
TV CHOSUN2 19 시대  /  ROI 3.1
TV CHOSUN2 20 시대  /  ROI 3.0
TV CHOSUN2 21 시대  /  ROI 3.3
TV CHOSUN2 22 시대  /  ROI 3.1
TV CHOSUN2 23 시대  /  ROI nan
cineF 10 시대  /  ROI 3.9
cineF 11 시대  /  ROI 5.1
cineF 12 시대  /  ROI 3.9
cineF 13 시대  /  ROI 4.7
cineF 14 시대  /  ROI 4.4
cineF 15 시대  /  ROI 5.3
cineF 16 시대  /  ROI 5.6
cineF 17 시대  /  ROI 3.1
cineF 18 시대  /  ROI 7.4
cineF 19 시대  /  ROI 5.5
cineF 20 시대  /  ROI 4.5
cineF 21 시대  /  ROI 1.9
cineF 22 시대  /  ROI 3.0
cineF 23 시대  /  ROI nan
CNTV 10 시대  /  ROI 4.0
CNTV 11 시대  /  ROI 4.0
CNTV 12 시대  /  ROI 4.3
CNTV 13 시대  /  ROI 3.4
CNTV 14 시대  /  ROI 4.1
CNTV 15 시대  /  ROI 3.9
CNTV 16 시대  /  ROI 4.0
CNTV 17 시대  /  ROI 3.5
CNTV 18 시대  /  ROI 4.0
CNTV 19 시대  /  ROI 3.9
CNTV 20 시대  /  ROI 4.1
CNTV 21 시대  /  ROI nan
CNTV 22 시대  /  ROI nan
CNTV 23 시대  /  ROI nan
SPOTV 10 시대  /  ROI 10.7
SPOTV 11 시대  /  ROI 10.3
SPOTV 12 시대  /  ROI 9.5
SPOTV 13 시대  /  ROI 8.8
SPOTV 14 시대  /  ROI 7.7
SPOTV 15 시대  /  ROI 9.5
SPOTV 16 시대  /  ROI 8.5
SPOTV 17 시대  /  ROI 6.5
SPOTV 18 시대  /  ROI 10.9
SPOTV 19 시대  /  ROI 11.9
SPOTV 20 시대  /  ROI 7.9
SPOTV 21 시대  /  ROI 11.9
SPOTV 22 시대  /  ROI nan
SPOTV 23 시대  /  ROI nan
YTN 10 시대  /  ROI nan
YTN 11 시대  /  ROI 1.1
YTN 12 시대  /  ROI nan
YTN 13 시대  /  ROI 0.9
YTN 14 시대  /  ROI 1.2
YTN 15 시대  /  ROI 1.0
YTN 16 시대  /  ROI nan
YTN 17 시대  /  ROI 0.9
YTN 18 시대  /  ROI 0.8
YTN 19 시대  /  ROI 1.2
YTN 20 시대  /  ROI 0.9
YTN 21 시대  /  ROI 1.3
YTN 22 시대  /  ROI nan
YTN 23 시대  /  ROI nan
CBS 10 시대  /  ROI 3.5
CBS 11 시대  /  ROI 2.8
CBS 12 시대  /  ROI 3.5
CBS 13 시대  /  ROI 2.8
CBS 14 시대  /  ROI 2.6
CBS 15 시대  /  ROI 2.5
CBS 16 시대  /  ROI 2.5
CBS 17 시대  /  ROI 3.4
CBS 18 시대  /  ROI 3.3
CBS 19 시대  /  ROI 3.3
CBS 20 시대  /  ROI 3.6
CBS 21 시대  /  ROI nan
CBS 22 시대  /  ROI nan
CBS 23 시대  /  ROI nan
NQQ 10 시대  /  ROI 4.8
NQQ 11 시대  /  ROI 3.5
NQQ 12 시대  /  ROI nan
NQQ 13 시대  /  ROI nan
NQQ 14 시대  /  ROI 3.5
NQQ 15 시대  /  ROI 3.5
NQQ 16 시대  /  ROI 3.5
NQQ 17 시대  /  ROI 3.5
NQQ 18 시대  /  ROI 3.5
NQQ 19 시대  /  ROI 3.5
NQQ 20 시대  /  ROI 3.5
NQQ 21 시대  /  ROI nan
NQQ 22 시대  /  ROI nan
NQQ 23 시대  /  ROI nan
KBS 스포츠 10 시대  /  ROI nan
KBS 스포츠 11 시대  /  ROI nan
KBS 스포츠 12 시대  /  ROI nan
KBS 스포츠 13 시대  /  ROI 1.6
KBS 스포츠 14 시대  /  ROI nan
KBS 스포츠 15 시대  /  ROI 1.6
KBS 스포츠 16 시대  /  ROI 1.6
KBS 스포츠 17 시대  /  ROI nan
KBS 스포츠 18 시대  /  ROI 1.6
KBS 스포츠 19 시대  /  ROI nan
KBS 스포츠 20 시대  /  ROI 1.6
KBS 스포츠 21 시대  /  ROI 1.6
KBS 스포츠 22 시대  /  ROI nan
KBS 스포츠 23 시대  /  ROI nan
SKY트래블 10 시대  /  ROI 11.0
SKY트래블 11 시대  /  ROI 6.3
SKY트래블 12 시대  /  ROI 8.6
SKY트래블 13 시대  /  ROI 7.9
SKY트래블 14 시대  /  ROI 10.1
SKY트래블 15 시대  /  ROI 9.0
SKY트래블 16 시대  /  ROI 8.9
SKY트래블 17 시대  /  ROI 12.5
SKY트래블 18 시대  /  ROI 9.2
SKY트래블 19 시대  /  ROI 9.6
SKY트래블 20 시대  /  ROI 8.6
SKY트래블 21 시대  /  ROI nan
SKY트래블 22 시대  /  ROI nan
SKY트래블 23 시대  /  ROI nan
CTS 10 시대  /  ROI 2.7
CTS 11 시대  /  ROI 2.0
CTS 12 시대  /  ROI 2.7
CTS 13 시대  /  ROI 3.0
CTS 14 시대  /  ROI 3.2
CTS 15 시대  /  ROI 3.7
CTS 16 시대  /  ROI 3.4
CTS 17 시대  /  ROI 3.6
CTS 18 시대  /  ROI 2.7
CTS 19 시대  /  ROI 3.2
CTS 20 시대  /  ROI 4.1
CTS 21 시대  /  ROI 5.5
CTS 22 시대  /  ROI nan
CTS 23 시대  /  ROI nan
SBS 10 시대  /  ROI 0.9
SBS 11 시대  /  ROI 2.7
SBS 12 시대  /  ROI 1.9
SBS 13 시대  /  ROI 1.4
SBS 14 시대  /  ROI 0.6
SBS 15 시대  /  ROI 1.2
SBS 16 시대  /  ROI 2.4
SBS 17 시대  /  ROI 0.7
SBS 18 시대  /  ROI 0.4
SBS 19 시대  /  ROI nan
SBS 20 시대  /  ROI nan
SBS 21 시대  /  ROI nan
SBS 22 시대  /  ROI nan
SBS 23 시대  /  ROI nan
채널A 10 시대  /  ROI 1.4
채널A 11 시대  /  ROI 1.1
채널A 12 시대  /  ROI 0.8
채널A 13 시대  /  ROI 0.8
채널A 14 시대  /  ROI 1.2
채널A 15 시대  /  ROI nan
채널A 16 시대  /  ROI 0.9
채널A 17 시대  /  ROI 1.1
채널A 18 시대  /  ROI 1.1
채널A 19 시대  /  ROI nan
채널A 20 시대  /  ROI 1.7
채널A 21 시대  /  ROI nan
채널A 22 시대  /  ROI nan
채널A 23 시대  /  ROI nan
JTBC4 10 시대  /  ROI 3.3
JTBC4 11 시대  /  ROI 7.8
JTBC4 12 시대  /  ROI 6.5
JTBC4 13 시대  /  ROI 3.9
JTBC4 14 시대  /  ROI 4.7
JTBC4 15 시대  /  ROI 7.9
JTBC4 16 시대  /  ROI 5.6
JTBC4 17 시대  /  ROI 6.1
JTBC4 18 시대  /  ROI 7.0
JTBC4 19 시대  /  ROI 7.5
JTBC4 20 시대  /  ROI 7.2
JTBC4 21 시대  /  ROI 5.0
JTBC4 22 시대  /  ROI 4.4
JTBC4 23 시대  /  ROI nan
TV조선 10 시대  /  ROI 2.7
TV조선 11 시대  /  ROI 1.0
TV조선 12 시대  /  ROI 6.7
TV조선 13 시대  /  ROI nan
TV조선 14 시대  /  ROI 0.9
TV조선 15 시대  /  ROI 0.7
TV조선 16 시대  /  ROI 1.2
TV조선 17 시대  /  ROI 0.9
TV조선 18 시대  /  ROI 0.5
TV조선 19 시대  /  ROI 0.4
TV조선 20 시대  /  ROI nan
TV조선 21 시대  /  ROI nan
TV조선 22 시대  /  ROI nan
TV조선 23 시대  /  ROI nan
평화방송 10 시대  /  ROI 4.6
평화방송 11 시대  /  ROI 6.1
평화방송 12 시대  /  ROI 6.4
평화방송 13 시대  /  ROI 5.1
평화방송 14 시대  /  ROI 5.2
평화방송 15 시대  /  ROI 8.5
평화방송 16 시대  /  ROI 5.8
평화방송 17 시대  /  ROI 5.1
평화방송 18 시대  /  ROI 11.7
평화방송 19 시대  /  ROI 4.8
평화방송 20 시대  /  ROI 4.9
평화방송 21 시대  /  ROI nan
평화방송 22 시대  /  ROI nan
평화방송 23 시대  /  ROI nan
GTV 10 시대  /  ROI 7.3
GTV 11 시대  /  ROI 9.3
GTV 12 시대  /  ROI 9.5
GTV 13 시대  /  ROI 9.2
GTV 14 시대  /  ROI 7.9
GTV 15 시대  /  ROI 8.1
GTV 16 시대  /  ROI nan
GTV 17 시대  /  ROI 7.3
GTV 18 시대  /  ROI 14.0
GTV 19 시대  /  ROI 10.0
GTV 20 시대  /  ROI 9.9
GTV 21 시대  /  ROI nan
GTV 22 시대  /  ROI nan
GTV 23 시대  /  ROI nan
SPOTV+ 10 시대  /  ROI 9.5
SPOTV+ 11 시대  /  ROI 18.2
SPOTV+ 12 시대  /  ROI 11.8
SPOTV+ 13 시대  /  ROI nan
SPOTV+ 14 시대  /  ROI 8.5
SPOTV+ 15 시대  /  ROI 7.2
SPOTV+ 16 시대  /  ROI 10.9
SPOTV+ 17 시대  /  ROI 8.8
SPOTV+ 18 시대  /  ROI 10.0
SPOTV+ 19 시대  /  ROI 7.5
SPOTV+ 20 시대  /  ROI 17.2
SPOTV+ 21 시대  /  ROI 13.0
SPOTV+ 22 시대  /  ROI nan
SPOTV+ 23 시대  /  ROI nan
MBC드라마 10 시대  /  ROI 2.4
MBC드라마 11 시대  /  ROI 1.9
MBC드라마 12 시대  /  ROI 2.5
MBC드라마 13 시대  /  ROI 1.4
MBC드라마 14 시대  /  ROI nan
MBC드라마 15 시대  /  ROI 1.8
MBC드라마 16 시대  /  ROI 2.6
MBC드라마 17 시대  /  ROI 1.9
MBC드라마 18 시대  /  ROI 1.4
MBC드라마 19 시대  /  ROI 2.5
MBC드라마 20 시대  /  ROI 1.1
MBC드라마 21 시대  /  ROI nan
MBC드라마 22 시대  /  ROI nan
MBC드라마 23 시대  /  ROI nan
KBS드라마 10 시대  /  ROI 1.4
KBS드라마 11 시대  /  ROI 1.1
KBS드라마 12 시대  /  ROI 0.7
KBS드라마 13 시대  /  ROI 0.6
KBS드라마 14 시대  /  ROI 0.8
KBS드라마 15 시대  /  ROI 1.0
KBS드라마 16 시대  /  ROI nan
KBS드라마 17 시대  /  ROI 1.6
KBS드라마 18 시대  /  ROI 1.6
KBS드라마 19 시대  /  ROI 1.0
KBS드라마 20 시대  /  ROI 1.1
KBS드라마 21 시대  /  ROI 0.6
KBS드라마 22 시대  /  ROI nan
KBS드라마 23 시대  /  ROI nan
SPOTV2 10 시대  /  ROI 15.3
SPOTV2 11 시대  /  ROI 8.0
SPOTV2 12 시대  /  ROI 11.0
SPOTV2 13 시대  /  ROI 12.6
SPOTV2 14 시대  /  ROI 9.2
SPOTV2 15 시대  /  ROI 10.9
SPOTV2 16 시대  /  ROI 9.2
SPOTV2 17 시대  /  ROI nan
SPOTV2 18 시대  /  ROI 9.5
SPOTV2 19 시대  /  ROI nan
SPOTV2 20 시대  /  ROI nan
SPOTV2 21 시대  /  ROI nan
SPOTV2 22 시대  /  ROI 5.6
SPOTV2 23 시대  /  ROI nan
하이라이트 10 시대  /  ROI 6.5
하이라이트 11 시대  /  ROI 4.1
하이라이트 12 시대  /  ROI 5.7
하이라이트 13 시대  /  ROI 3.4
하이라이트 14 시대  /  ROI 5.6
하이라이트 15 시대  /  ROI 5.8
하이라이트 16 시대  /  ROI 4.1
하이라이트 17 시대  /  ROI 6.2
하이라이트 18 시대  /  ROI 5.4
하이라이트 19 시대  /  ROI 5.8
하이라이트 20 시대  /  ROI 4.4
하이라이트 21 시대  /  ROI 5.4

하이라이트 22 시대  /  ROI nan
하이라이트 23 시대  /  ROI nan
Ch.View 10 시대  /  ROI 2.6
Ch.View 11 시대  /  ROI 2.4
Ch.View 12 시대  /  ROI 2.3
Ch.View 13 시대  /  ROI 1.0
Ch.View 14 시대  /  ROI 3.1
Ch.View 15 시대  /  ROI 3.1
Ch.View 16 시대  /  ROI nan
Ch.View 17 시대  /  ROI nan
Ch.View 18 시대  /  ROI 2.9
Ch.View 19 시대  /  ROI 2.6
Ch.View 20 시대  /  ROI nan
Ch.View 21 시대  /  ROI nan
Ch.View 22 시대  /  ROI nan
Ch.View 23 시대  /  ROI nan
DramaH 10 시대  /  ROI 4.6
DramaH 11 시대  /  ROI 4.2
DramaH 12 시대  /  ROI 7.0
DramaH 13 시대  /  ROI nan
DramaH 14 시대  /  ROI 5.1
DramaH 15 시대  /  ROI 5.3
DramaH 16 시대  /  ROI 6.6
DramaH 17 시대  /  ROI 3.5
DramaH 18 시대  /  ROI 6.7
DramaH 19 시대  /  ROI 7.7
DramaH 20 시대  /  ROI 4.3
DramaH 21 시대  /  ROI nan
DramaH 22 시대  /  ROI nan
DramaH 23 시대  /  ROI nan
MBN 10 시대  /  ROI 0.6
MBN 11 시대  /  ROI nan
MBN 12 시대  /  ROI nan
MBN 13 시대  /  ROI 0.7
MBN 14 시대  /  ROI nan
MBN 15 시대  /  ROI nan
MBN 16 시대  /  ROI 1.4
MBN 17 시대  /  ROI nan
MBN 18 시대  /  ROI 0.2
MBN 19 시대  /  ROI nan
MBN 20 시대  /  ROI nan
MBN 21 시대  /  ROI 0.1
MBN 22 시대  /  ROI nan
MBN 23 시대  /  ROI nan
Dramax 10 시대  /  ROI nan
Dramax 11 시대  /  ROI 2.1
Dramax 12 시대  /  ROI nan
Dramax 13 시대  /  ROI 2.9
Dramax 14 시대  /  ROI nan
Dramax 15 시대  /  ROI nan
Dramax 16 시대  /  ROI 5.4
Dramax 17 시대  /  ROI 3.4
Dramax 18 시대  /  ROI nan
Dramax 19 시대  /  ROI nan
Dramax 20 시대  /  ROI 2.5
Dramax 21 시대  /  ROI 3.7
Dramax 22 시대  /  ROI nan
Dramax 23 시대  /  ROI nan
KBS2 10 시대  /  ROI 0.5
KBS2 11 시대  /  ROI nan
KBS2 12 시대  /  ROI nan
KBS2 13 시대  /  ROI nan
KBS2 14 시대  /  ROI nan
KBS2 15 시대  /  ROI nan
KBS2 16 시대  /  ROI nan
KBS2 17 시대  /  ROI 0.4
KBS2 18 시대  /  ROI nan
KBS2 19 시대  /  ROI nan
KBS2 20 시대  /  ROI nan
KBS2 21 시대  /  ROI nan
KBS2 22 시대  /  ROI nan
KBS2 23 시대  /  ROI nan
BBS 10 시대  /  ROI nan
BBS 11 시대  /  ROI 8.4
BBS 12 시대  /  ROI nan
BBS 13 시대  /  ROI nan
BBS 14 시대  /  ROI 11.2
BBS 15 시대  /  ROI nan
BBS 16 시대  /  ROI nan
BBS 17 시대  /  ROI nan
BBS 18 시대  /  ROI 7.4
BBS 19 시대  /  ROI 7.4
BBS 20 시대  /  ROI nan
BBS 21 시대  /  ROI nan
BBS 22 시대  /  ROI nan
BBS 23 시대  /  ROI nan
SKY펫파크 10 시대  /  ROI 6.7
SKY펫파크 11 시대  /  ROI 8.0
SKY펫파크 12 시대  /  ROI nan
SKY펫파크 13 시대  /  ROI 5.3
SKY펫파크 14 시대  /  ROI 5.0
SKY펫파크 15 시대  /  ROI 5.0
SKY펫파크 16 시대  /  ROI nan
SKY펫파크 17 시대  /  ROI 8.9
SKY펫파크 18 시대  /  ROI 7.0
SKY펫파크 19 시대  /  ROI 7.4
SKY펫파크 20 시대  /  ROI 3.5
SKY펫파크 21 시대  /  ROI nan
SKY펫파크 22 시대  /  ROI nan
SKY펫파크 23 시대  /  ROI nan
MBC ON 10 시대  /  ROI 3.5
MBC ON 11 시대  /  ROI nan
MBC ON 12 시대  /  ROI nan
MBC ON 13 시대  /  ROI 2.2
MBC ON 14 시대  /  ROI nan
MBC ON 15 시대  /  ROI nan
MBC ON 16 시대  /  ROI nan
MBC ON 17 시대  /  ROI nan
MBC ON 18 시대  /  ROI nan
MBC ON 19 시대  /  ROI 2.7
MBC ON 20 시대  /  ROI 3.3
MBC ON 21 시대  /  ROI 2.9
MBC ON 22 시대  /  ROI nan
MBC ON 23 시대  /  ROI nan
더라이프 10 시대  /  ROI nan
더라이프 11 시대  /  ROI nan
더라이프 12 시대  /  ROI nan
더라이프 13 시대  /  ROI nan
더라이프 14 시대  /  ROI nan
더라이프 15 시대  /  ROI nan
더라이프 16 시대  /  ROI 7.0
더라이프 17 시대  /  ROI nan
더라이프 18 시대  /  ROI nan
더라이프 19 시대  /  ROI nan
더라이프 20 시대  /  ROI nan
더라이프 21 시대  /  ROI nan
더라이프 22 시대  /  ROI nan
더라이프 23 시대  /  ROI nan
EDGETV 10 시대  /  ROI nan
EDGETV 11 시대  /  ROI nan
EDGETV 12 시대  /  ROI 1.9
EDGETV 13 시대  /  ROI 1.9
EDGETV 14 시대  /  ROI nan
EDGETV 15 시대  /  ROI nan
EDGETV 16 시대  /  ROI 2.0
EDGETV 17 시대  /  ROI nan
EDGETV 18 시대  /  ROI nan
EDGETV 19 시대  /  ROI nan
EDGETV 20 시대  /  ROI nan
EDGETV 21 시대  /  ROI nan
EDGETV 22 시대  /  ROI nan
EDGETV 23 시대  /  ROI nan
채널차이나 10 시대  /  ROI nan
채널차이나 11 시대  /  ROI nan
채널차이나 12 시대  /  ROI nan
채널차이나 13 시대  /  ROI 7.1
채널차이나 14 시대  /  ROI nan
채널차이나 15 시대  /  ROI 5.8
채널차이나 16 시대  /  ROI nan
채널차이나 17 시대  /  ROI nan
채널차이나 18 시대  /  ROI nan
채널차이나 19 시대  /  ROI nan
채널차이나 20 시대  /  ROI nan
채널차이나 21 시대  /  ROI nan
채널차이나 22 시대  /  ROI nan
채널차이나 23 시대  /  ROI nan
BTN 10 시대  /  ROI nan
BTN 11 시대  /  ROI nan
BTN 12 시대  /  ROI nan
BTN 13 시대  /  ROI 2.6
BTN 14 시대  /  ROI nan
BTN 15 시대  /  ROI nan
BTN 16 시대  /  ROI nan
BTN 17 시대  /  ROI 5.3
BTN 18 시대  /  ROI nan
BTN 19 시대  /  ROI nan
BTN 20 시대  /  ROI 8.8
BTN 21 시대  /  ROI nan
BTN 22 시대  /  ROI nan
BTN 23 시대  /  ROI nan
FX 10 시대  /  ROI nan
FX 11 시대  /  ROI nan
FX 12 시대  /  ROI nan
FX 13 시대  /  ROI nan
FX 14 시대  /  ROI nan
FX 15 시대  /  ROI nan
FX 16 시대  /  ROI nan
FX 17 시대  /  ROI nan
FX 18 시대  /  ROI nan
FX 19 시대  /  ROI 4.0
FX 20 시대  /  ROI 30.2
FX 21 시대  /  ROI nan
FX 22 시대  /  ROI 2.0
FX 23 시대  /  ROI nan
SPOTVG&H 10 시대  /  ROI nan
SPOTVG&H 11 시대  /  ROI 9.0
SPOTVG&H 12 시대  /  ROI 9.0
SPOTVG&H 13 시대  /  ROI 9.0
SPOTVG&H 14 시대  /  ROI nan
SPOTVG&H 15 시대  /  ROI nan
SPOTVG&H 16 시대  /  ROI nan
SPOTVG&H 17 시대  /  ROI nan
SPOTVG&H 18 시대  /  ROI nan
SPOTVG&H 19 시대  /  ROI 8.7
SPOTVG&H 20 시대  /  ROI nan
SPOTVG&H 21 시대  /  ROI nan
SPOTVG&H 22 시대  /  ROI nan
SPOTVG&H 23 시대  /  ROI nan
채널J 10 시대  /  ROI 5.5
채널J 11 시대  /  ROI nan
채널J 12 시대  /  ROI nan
채널J 13 시대  /  ROI nan
채널J 14 시대  /  ROI nan
채널J 15 시대  /  ROI nan
채널J 16 시대  /  ROI 11.3
채널J 17 시대  /  ROI nan
채널J 18 시대  /  ROI nan
채널J 19 시대  /  ROI 8.8
채널J 20 시대  /  ROI 6.0
채널J 21 시대  /  ROI nan
채널J 22 시대  /  ROI nan
채널J 23 시대  /  ROI nan
채널A+ 10 시대  /  ROI nan
채널A+ 11 시대  /  ROI nan
채널A+ 12 시대  /  ROI 7.1
채널A+ 13 시대  /  ROI nan
채널A+ 14 시대  /  ROI nan
채널A+ 15 시대  /  ROI nan
채널A+ 16 시대  /  ROI nan
채널A+ 17 시대  /  ROI 7.1
채널A+ 18 시대  /  ROI 7.1
채널A+ 19 시대  /  ROI 11.4
채널A+ 20 시대  /  ROI nan
채널A+ 21 시대  /  ROI nan
채널A+ 22 시대  /  ROI nan
채널A+ 23 시대  /  ROI nan
SKY드라마 10 시대  /  ROI nan
SKY드라마 11 시대  /  ROI nan
SKY드라마 12 시대  /  ROI nan
SKY드라마 13 시대  /  ROI nan
SKY드라마 14 시대  /  ROI nan
SKY드라마 15 시대  /  ROI nan
SKY드라마 16 시대  /  ROI nan
SKY드라마 17 시대  /  ROI nan
SKY드라마 18 시대  /  ROI nan
SKY드라마 19 시대  /  ROI 2.0
SKY드라마 20 시대  /  ROI 3.6
SKY드라마 21 시대  /  ROI nan
SKY드라마 22 시대  /  ROI nan
SKY드라마 23 시대  /  ROI nan
D-ONE 10 시대  /  ROI nan
D-ONE 11 시대  /  ROI nan
D-ONE 12 시대  /  ROI 3.1
D-ONE 13 시대  /  ROI nan
D-ONE 14 시대  /  ROI nan
D-ONE 15 시대  /  ROI nan
D-ONE 16 시대  /  ROI nan
D-ONE 17 시대  /  ROI nan
D-ONE 18 시대  /  ROI nan
D-ONE 19 시대  /  ROI nan
D-ONE 20 시대  /  ROI 2.7
D-ONE 21 시대  /  ROI nan
D-ONE 22 시대  /  ROI nan
D-ONE 23 시대  /  ROI nan
Olive 10 시대  /  ROI nan
Olive 11 시대  /  ROI 4.0
Olive 12 시대  /  ROI nan
Olive 13 시대  /  ROI nan
Olive 14 시대  /  ROI nan
Olive 15 시대  /  ROI nan
Olive 16 시대  /  ROI nan
Olive 17 시대  /  ROI nan
Olive 18 시대  /  ROI nan
Olive 19 시대  /  ROI nan
Olive 20 시대  /  ROI nan
Olive 21 시대  /  ROI nan
Olive 22 시대  /  ROI nan
Olive 23 시대  /  ROI nan
리얼TV 10 시대  /  ROI nan
리얼TV 11 시대  /  ROI nan
리얼TV 12 시대  /  ROI nan
리얼TV 13 시대  /  ROI 9.8
리얼TV 14 시대  /  ROI nan
리얼TV 15 시대  /  ROI nan
리얼TV 16 시대  /  ROI nan
리얼TV 17 시대  /  ROI nan
리얼TV 18 시대  /  ROI nan
리얼TV 19 시대  /  ROI nan
리얼TV 20 시대  /  ROI 4.9
리얼TV 21 시대  /  ROI nan
리얼TV 22 시대  /  ROI nan
리얼TV 23 시대  /  ROI nan
EBS키즈 10 시대  /  ROI 10.3
EBS키즈 11 시대  /  ROI nan
EBS키즈 12 시대  /  ROI nan
EBS키즈 13 시대  /  ROI nan
EBS키즈 14 시대  /  ROI nan
EBS키즈 15 시대  /  ROI nan
EBS키즈 16 시대  /  ROI nan
EBS키즈 17 시대  /  ROI nan
EBS키즈 18 시대  /  ROI nan
EBS키즈 19 시대  /  ROI nan
EBS키즈 20 시대  /  ROI nan
EBS키즈 21 시대  /  ROI nan
EBS키즈 22 시대  /  ROI nan
EBS키즈 23 시대  /  ROI nan

       0
0    0.7
1    0.9
2    2.1
3    1.5
4    1.2
..   ...
639  NaN
640  NaN
641  NaN
642  NaN
643  NaN

[644 rows x 1 columns]

In [19]:
b = pd.DataFrame()
c = []
for j in range(0,46,1) :
    for i in range(0,len(arr),14):
        a = arr[i:13*(i+2)].reset_index(drop = True)
        b = pd.concat([b,a],1).reset_index(drop = True)
    bb = b.head(14)
    channel =  by_ch['Channel'][j]
    c.append(channel)
#bb.columns=[c]
#bb.index=['10','11','12','13','14','15','16','17','18','19','20','21','22','23']
#bb.to_excel('./Datas/channel_ROI_test.xlsx')

In [20]:
ch_roi = pd.read_excel("./datas/channel_ROI.xlsx")
ch_roi.drop(['Unnamed: 0'],axis=1, inplace=True)
ch_roi.index=['10시','11시','12시','13시','14시','15시','16시','17시','18시','19시','20시','21시','22시','23시']
ch_roi.columns=[c]
ch_roi.to_excel('./Datas/df_channel_ROI_2.xlsx')

,EBS,MBN Plus,연합뉴스,씨채널,TV CHOSUN2,cineF,CNTV,SPOTV,YTN,CBS,...,BTN,FX,SPOTVG&H,채널J,채널A+,SKY드라마,D-ONE,Olive,리얼TV,EBS키즈
10시,0.720000,4.638488,NaN,11.618438,2.583754,3.901364,4.005634,10.732273,NaN,3.504048,...,NaN,NaN,NaN,5.545,NaN,NaN,NaN,NaN,NaN,10.335
11시,0.873333,4.752130,1.459924,11.427766,3.944000,5.108929,3.955833,10.281806,1.081308,2.777200,...,NaN,NaN,9.00,NaN,NaN,NaN,NaN,4.01,NaN,NaN
12시,2.087170,4.698796,1.282651,11.193582,2.533883,3.915164,4.301905,9.519434,NaN,3.511324,...,NaN,NaN,9.00,NaN,7.12,NaN,3.08,NaN,NaN,NaN
13시,1.503012,4.681771,1.312900,11.512229,2.490769,4.722150,3.423846,8.849063,0.915556,2.834783,...,2.64,NaN,9.00,NaN,NaN,NaN,NaN,NaN,9.84,NaN
14시,1.171852,4.643917,1.299507,10.974503,2.645116,4.398889,4.053789,7.729846,1.243600,2.604286,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15시,1.497647,4.728893,1.945000,11.020286,2.816711,5.346832,3.917000,9.520652,0.982593,2.486250,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16시,1.543704,4.791233,1.030000,11.551661,3.253041,5.603936,4.041500,8.451563,NaN,2.506667,...,NaN,NaN,NaN,11.340,NaN,NaN,NaN,NaN,NaN,NaN
17시,1.539920,4.602388,1.756000,11.287132,2.978538,3.132667,3.548750,6.540000,0.900000,3.448667,...,5.28,NaN,NaN,NaN,7.12,NaN,NaN,NaN,NaN,NaN
18시,2.077960,4.757236,1.170391,15.460084,3.312115,7.429524,3.957609,10.888889,0.850000,3.295385,...,NaN,NaN,NaN,NaN,7.12,NaN,NaN,NaN,NaN,NaN
19시,1.872793,4.622804,1.555642,14.169412,3.113408,5.495000,3.937872,11.919400,1.241128,3.309649,...,NaN,4.03,8.69,8.820,11.39,2.015,NaN,NaN,NaN,NaN
20시,1.701192,4.613049,1.592545,11.776935,3.006609,4.530000,4.077280,7.917143,0.907778,3.605000,...,8.80,30.24,NaN,6.050,NaN,3.630,2.74,NaN,4.92,NaN
21시,1.416452,4.769512,0.893333,15.676500,3.328333,1.885000,NaN,11.867778,1.297171,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22시,1.117316,4.622727,1.330000,NaN,3.070000,3.020000,NaN,NaN,NaN,NaN,...,NaN,2.02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23시,0.505000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN